### ISSUE TITLE
Log directory $HOME/.rsync-time-backup is empty

### ISSUE THREAD

**Issue by jesusguevarautomotriz** [basnijholt/rsync-time-machine.py#23] opened 2023-06-09 04:14 UTC
I got a message: "Backup completed without errors". (690GB). But when I want to check the log-file to take a look at what it has backed up or detect some "error", the $HOME/.rsync-time-backup directory is empty.
![Screenshot 2023-06-09 002914](https://github.com/basnijholt/rsync-time-machine.py/assets/8184794/0ded7ef6-5cb1-4aff-b9ca-46e3d4b5b463)

**Comment by basnijholt** [comment] 2023-06-11 18:33
Thanks for reporting.

It turns out this is a regression, this worked in v1.0.0, but in v1.1.0 I added an option to print all output using `-v`. I will add a test and fix this.

**Comment by basnijholt** [comment] 2023-06-11 20:21
Actually, it turns out the default for `auto_delete_log=True`: https://github.com/basnijholt/rsync-time-machine.py/blob/062f6d51ab82600288a3d38b0e683a5ba9e60170/rsync_time_machine.py#L905

This means that when there are no errors, the log will automatically be deleted.

**Comment by basnijholt** [comment] 2023-06-11 20:39
This did highlight another error, `auto_delete_log` should be set to False when specifying `--log-dir`, fixed in #24.

So whenever an error occurred or when using `--log-dir` the log files are preserved. When not using `--log-dir` and no errors, the log file will be deleted.

**Closed by basnijholt** 2023-06-11 20:39 UTC
